### PR TITLE
Fix links in README

### PR DESCRIPTION
**Pull request by xuebinglee**
:koala:

A few broken links in README are fixed.

/cc @zendesk/quokka

### Risks
 - None (Those links are already broken)

### CODE REVIEW

**Comment by adammw** [comment]
:+1:

**Comment by sandlerr** [comment]
does anyone actually use mailto links? maybe we can point to https://support.zendesk.com/hc ?

**Comment by sandlerr** [comment]
:+1:

**Comment by xuebinglee** [comment]
@sandlerr Dunno. I like HC better. I'll change it to https://support.zendesk.com/hc.

**Pull request merged**
