### PR TITLE
initial push

### PR DESCRIPTION
**Pull request by dpawluk**
Adds a JWT App to our demo applications. 
@maximeprades @pmgrove not sure what the review process is for this but let me know if I need to add anyone else or make changes.

### CODE REVIEW

**Comment by sandlerr** [comment]
Looks good! Is this complete as is or will you add some UI? I think as a best practice we should add [whitelisted urls](https://github.com/zendesk/demo_apps/blob/master/secure_requests_sample_app/manifest.json#L10) and set the `iss` claim as the subdomain, user's email, or some other setting that is likely to be unique per-account.

**Comment by dpawluk** [comment]
@sandlerr 
All good suggestions, shouldn't take too much to implement. I would ad a UI, but it seems (like the commonJS demo app) that it wouldn't benefit too terribly from it? What did you have in mind? I'll go ahead and add the whitlisted urls. I figured the best case for demoing this is using requestb.in. Do you think that hardcoding the values for subdomain and creating a paramter for the requestb.in URI would be a good solution? I wanted to keep it as simple as possible so demoing it doesn't involve a lot of steps.

**Comment by dpawluk** [comment]
@sandlerr 
for iss, should that be the zendesk subdomain? Thats what i did in the latest commit. Let me know if this works and what kind of interface might be appropriate.

**Comment by sandlerr** [comment]
This is great as is, requestb.in should provide enough UI for people to see how the request looks. Maybe we should link to http://jwt.io/ or similar to help people debug / decode their messages.

**Comment by dpawluk** [comment]
Cool, I just added the link to jwt.io to the README. At this point I think I just need a +1

@sandlerr

**Comment by sandlerr** [comment]
:+1: cc @zendesk/vegemite

**Comment by maximeprades** [comment]
logos aren't the correct ones. 

See here for instance:

https://github.com/zendesk/demo_apps/blob/master/basic_user_sample_app/assets/logo-small.png

**Comment by maximeprades** [comment]
other than that :+1:

**Pull request merged**
